controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

gripper_controller:
  ros__parameters:
    joints:
      - gripper_left_joint
      - gripper_right_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: true
