artifact_location: /home/nathan/Documents/GitHub/exploration_and_research_turtlebot/tb3_autonomy/ai_fine_tuning/runs/mlflow/488087800681908052
creation_time: 1769027961681
experiment_id: '488087800681908052'
last_update_time: 1769027961681
lifecycle_stage: active
name: /home/nathan/Documents/GitHub/exploration_and_research_turtlebot/tb3_autonomy/ai_fine_tuning/runs/detect
